
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_Standard(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		 reg    [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire RxD;
reg seg7_disp_off_signal;

parameter req_byte_length = 3;
parameter storage_length = 784;
reg transmit;
wire tick;
wire [7:0] receive_data;
//reg [7:0] count_value;
wire receive_done;
wire [7:0] mem_data;
reg [31:0] mem_address;
reg [31:0] written_mem_address;
reg mem_wr;
reg first_val_receive;
reg txdone_flag;
reg [7:0] pixels[storage_length*req_byte_length-1:0];
reg [23:0] Encrypted_pixels[storage_length-1:0];
reg [23:0] encrypted_pixel_temp_store;
reg [9:0] encrypted_pixel_address;
reg [23:0] Label;
reg [7:0] serial_transmit_reg;
reg [7:0] count_bytes;
reg [7:0] count_label_bytes;

// defining the registers for each node of decision tree
reg Allpixel_receive_complete;
reg [15:0] state;
reg ml_inference_completed;


//=======================================================
//  Structural coding
//=======================================================


Binary_To_7Segment seg1 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label[3:0] : mem_address[3:0]),  .o_Segment_A(HEX0[0]), .o_Segment_B(HEX0[1]),  .o_Segment_C(HEX0[2]), 
                          .o_Segment_D(HEX0[3]), .o_Segment_E(HEX0[4]), .o_Segment_F(HEX0[5]), .o_Segment_G(HEX0[6]));
								  
Binary_To_7Segment seg2 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label[7:4] : mem_address[7:4]),  .o_Segment_A(HEX1[0]), .o_Segment_B(HEX1[1]),  .o_Segment_C(HEX1[2]), 
                          .o_Segment_D(HEX1[3]), .o_Segment_E(HEX1[4]), .o_Segment_F(HEX1[5]), .o_Segment_G(HEX1[6]));
								  
Binary_To_7Segment seg3 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label[11:8] : mem_address[9:8]),  .o_Segment_A(HEX2[0]), .o_Segment_B(HEX2[1]),  .o_Segment_C(HEX2[2]), 
                          .o_Segment_D(HEX2[3]), .o_Segment_E(HEX2[4]), .o_Segment_F(HEX2[5]), .o_Segment_G(HEX2[6]));
								  
								  
Binary_To_7Segment seg4 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label[15:12] : written_mem_address[3:0]),  .o_Segment_A(HEX3[0]), .o_Segment_B(HEX3[1]),  .o_Segment_C(HEX3[2]), 
                          .o_Segment_D(HEX3[3]), .o_Segment_E(HEX3[4]), .o_Segment_F(HEX3[5]), .o_Segment_G(HEX3[6]));
								  
Binary_To_7Segment seg5 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label[19:16] : written_mem_address[7:4]),  .o_Segment_A(HEX4[0]), .o_Segment_B(HEX4[1]),  .o_Segment_C(HEX4[2]), 
                          .o_Segment_D(HEX4[3]), .o_Segment_E(HEX4[4]), .o_Segment_F(HEX4[5]), .o_Segment_G(HEX4[6]));
								  
Binary_To_7Segment seg6 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'd0: written_mem_address[9:8]),  .o_Segment_A(HEX5[0]), .o_Segment_B(HEX5[1]),  .o_Segment_C(HEX5[2]), 
                          .o_Segment_D(HEX5[3]), .o_Segment_E(HEX5[4]), .o_Segment_F(HEX5[5]), .o_Segment_G(HEX5[6]));

					  
								  
assign RxD = GPIO[0];  //UART receiver pin for FPGA
// GPIO[1];  //UART transmitter Pin for FPGA


uart_rx R3 (.i_Clock(CLOCK_50), .i_Rx_Serial(RxD), .o_Rx_DV(receive_done), .o_Rx_Byte(receive_data) );

always @ (posedge receive_done)
begin
      if (SW[0] == 1)    begin LEDR[1] <= 0; end
      else begin LEDR[1] <= ~LEDR[1]; end
end

always @ (posedge CLOCK_50)
begin
    if (SW[0] == 1)
         begin
            count_label_bytes <= 0;
            count_bytes <= 0;
            first_val_receive <= 0;
            mem_address <= 0;
            mem_wr <=0;
            encrypted_pixel_address <= 0;
				seg7_disp_off_signal <=0;
         end
		else if (receive_done == 1)
        begin
			  pixels[mem_address] <= receive_data;
			  count_bytes <= count_bytes+1;
				case (count_bytes[1:0])
					2'b00: encrypted_pixel_temp_store[23:16] <= receive_data;
					2'b01: encrypted_pixel_temp_store[15:8] <= receive_data;
					2'b10: encrypted_pixel_temp_store[7:0] <= receive_data;
					 
				endcase
			  mem_address <= mem_address+1; written_mem_address <= mem_address;         
			  if (count_bytes == req_byte_length-1)
					begin
						count_bytes <= 0;
						Encrypted_pixels[encrypted_pixel_address] <= {encrypted_pixel_temp_store[23:8], receive_data};
						encrypted_pixel_address <= encrypted_pixel_address + 1;
						if (encrypted_pixel_address >= storage_length-1)
							begin Allpixel_receive_complete <=1; end
						else
							begin Allpixel_receive_complete <=0; end
					end
        end
     
     if (tick == 1)
         begin
           if (txdone_flag == 0 )
               begin
                    txdone_flag <= 1;
               end
           else 
               begin
                    mem_address <= mem_address+1;
                    txdone_flag <= 0;
               end              
         end
     
     if (mem_address < written_mem_address && SW[1]== 1)
     begin
        transmit <= 1;    
        serial_transmit_reg <= pixels[mem_address];    
     end
     else if (mem_address > written_mem_address && mem_address <= written_mem_address+req_byte_length && ml_inference_completed == 1 && SW[1]== 1)
     begin  
        if (count_label_bytes == 0)
        begin  serial_transmit_reg <= Label[23:16]; end 
        if (count_label_bytes == 1)
        begin  serial_transmit_reg <= Label[15:8]; end 
        if (count_label_bytes == 2)
        begin  serial_transmit_reg <= Label[7:0]; end   
        if (tick == 1 && txdone_flag == 1)
        begin count_label_bytes <= count_label_bytes+1; end
        transmit <= 1; 
     end
     else
     begin
        transmit <=0; 
     end 
	  
	  if (SW[2] == 1)
         begin
				seg7_disp_off_signal <= 1;
         end
end

uart_tx T1 (.i_Clock(CLOCK_50), .i_Tx_DV(transmit), .i_Tx_Byte(serial_transmit_reg), .o_Tx_Active(), .o_Tx_Serial(GPIO[1]), .o_Tx_Done(tick) );



always @ (posedge CLOCK_50)
    begin
    if (SW[0] == 1)
         begin
            state <= 0;
         end
         
    if (Allpixel_receive_complete==1)
        begin
 case (state)


16'd0:if (Encrypted_pixels[350] <= 3382175) begin state<=1; end  else begin state<=256; end 
 
16'd1:if (Encrypted_pixels[568] <= 1523081) begin state<=2; end  else begin state<=129; end 
 
16'd2:if (Encrypted_pixels[430] <= 1523081) begin state<=3; end  else begin state<=66; end 
 
16'd3:if (Encrypted_pixels[405] <= 1541028) begin state<=4; end  else begin state<=35; end 
 
16'd4:if (Encrypted_pixels[485] <= 1882847) begin state<=5; end  else begin state<=20; end 
 
16'd5:if (Encrypted_pixels[154] <= 1532484) begin state<=6; end  else begin state<=13; end 
 
16'd6:if (Encrypted_pixels[594] <= 1882847) begin state<=7; end  else begin state<=10; end 
 
16'd7:if (Encrypted_pixels[156] <= 1523081) begin Label<=1612420; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd10:if (Encrypted_pixels[481] <= 1739301) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd13:if (Encrypted_pixels[510] <= 1671222) begin state<=14; end  else begin state<=17; end 
 
16'd14:if (Encrypted_pixels[544] <= 1573621) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd17:if (Encrypted_pixels[399] <= 1845940) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd20:if (Encrypted_pixels[211] <= 2342477) begin state<=21; end  else begin state<=28; end 
 
16'd21:if (Encrypted_pixels[487] <= 3457326) begin state<=22; end  else begin state<=25; end 
 
16'd22:if (Encrypted_pixels[572] <= 3132640) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd25:if (Encrypted_pixels[427] <= 1541028) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd28:if (Encrypted_pixels[427] <= 1523081) begin state<=29; end  else begin state<=32; end 
 
16'd29:if (Encrypted_pixels[154] <= 1532484) begin Label<=1612420; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd32:if (Encrypted_pixels[437] <= 1532484) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd35:if (Encrypted_pixels[516] <= 1523081) begin state<=36; end  else begin state<=51; end 
 
16'd36:if (Encrypted_pixels[353] <= 1523081) begin state<=37; end  else begin state<=44; end 
 
16'd37:if (Encrypted_pixels[322] <= 1591075) begin state<=38; end  else begin state<=41; end 
 
16'd38:if (Encrypted_pixels[355] <= 1734205) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd41:if (Encrypted_pixels[546] <= 1541028) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd44:if (Encrypted_pixels[346] <= 1532484) begin state<=45; end  else begin state<=48; end 
 
16'd45:if (Encrypted_pixels[652] <= 2391907) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd48:if (Encrypted_pixels[210] <= 1591075) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd51:if (Encrypted_pixels[658] <= 1612420) begin state<=52; end  else begin state<=59; end 
 
16'd52:if (Encrypted_pixels[351] <= 4799899) begin state<=53; end  else begin state<=56; end 
 
16'd53:if (Encrypted_pixels[242] <= 1523081) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd56:if (Encrypted_pixels[208] <= 1532484) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd59:if (Encrypted_pixels[376] <= 1541028) begin state<=60; end  else begin state<=63; end 
 
16'd60:if (Encrypted_pixels[634] <= 1974822) begin Label<=1612420; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd63:if (Encrypted_pixels[434] <= 2707068) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd66:if (Encrypted_pixels[211] <= 2009277) begin state<=67; end  else begin state<=98; end 
 
16'd67:if (Encrypted_pixels[543] <= 2939774) begin state<=68; end  else begin state<=83; end 
 
16'd68:if (Encrypted_pixels[267] <= 3408443) begin state<=69; end  else begin state<=76; end 
 
16'd69:if (Encrypted_pixels[155] <= 2633922) begin state<=70; end  else begin state<=73; end 
 
16'd70:if (Encrypted_pixels[97] <= 1543571) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd73:if (Encrypted_pixels[510] <= 1786619) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd76:if (Encrypted_pixels[353] <= 1532484) begin state<=77; end  else begin state<=80; end 
 
16'd77:if (Encrypted_pixels[411] <= 1734205) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1612420; state<=0;ml_inference_completed<=1; end 

16'd80:if (Encrypted_pixels[405] <= 1739301) begin Label<=1612420; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd83:if (Encrypted_pixels[271] <= 1532484) begin state<=84; end  else begin state<=91; end 
 
16'd84:if (Encrypted_pixels[269] <= 2939774) begin state<=85; end  else begin state<=88; end 
 
16'd85:if (Encrypted_pixels[273] <= 2289429) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd88:if (Encrypted_pixels[269] <= 5134336) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd91:if (Encrypted_pixels[155] <= 1671222) begin state<=92; end  else begin state<=95; end 
 
16'd92:if (Encrypted_pixels[267] <= 3289984) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd95:if (Encrypted_pixels[407] <= 1543571) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd98:if (Encrypted_pixels[156] <= 1523081) begin state<=99; end  else begin state<=114; end 
 
16'd99:if (Encrypted_pixels[381] <= 1674367) begin state<=100; end  else begin state<=107; end 
 
16'd100:if (Encrypted_pixels[217] <= 1543571) begin state<=101; end  else begin state<=104; end 
 
16'd101:if (Encrypted_pixels[542] <= 2550936) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd104:if (Encrypted_pixels[384] <= 2063926) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd107:if (Encrypted_pixels[317] <= 1523081) begin state<=108; end  else begin state<=111; end 
 
16'd108:if (Encrypted_pixels[342] <= 1532484) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd111:if (Encrypted_pixels[212] <= 1532484) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd114:if (Encrypted_pixels[101] <= 1532484) begin state<=115; end  else begin state<=122; end 
 
16'd115:if (Encrypted_pixels[571] <= 1591075) begin state<=116; end  else begin state<=119; end 
 
16'd116:if (Encrypted_pixels[655] <= 1532484) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd119:if (Encrypted_pixels[435] <= 1612420) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd122:if (Encrypted_pixels[538] <= 2606099) begin state<=123; end  else begin state<=126; end 
 
16'd123:if (Encrypted_pixels[270] <= 2566113) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd126:if (Encrypted_pixels[543] <= 1707208) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd129:if (Encrypted_pixels[435] <= 1523081) begin state<=130; end  else begin state<=193; end 
 
16'd130:if (Encrypted_pixels[489] <= 1734205) begin state<=131; end  else begin state<=162; end 
 
16'd131:if (Encrypted_pixels[380] <= 1541028) begin state<=132; end  else begin state<=147; end 
 
16'd132:if (Encrypted_pixels[324] <= 4085730) begin state<=133; end  else begin state<=140; end 
 
16'd133:if (Encrypted_pixels[73] <= 1636686) begin state<=134; end  else begin state<=137; end 
 
16'd134:if (Encrypted_pixels[455] <= 1523081) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd137:if (Encrypted_pixels[577] <= 1591075) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd140:if (Encrypted_pixels[427] <= 2600515) begin state<=141; end  else begin state<=144; end 
 
16'd141:if (Encrypted_pixels[240] <= 3082054) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd144:if (Encrypted_pixels[237] <= 1532484) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd147:if (Encrypted_pixels[456] <= 1674367) begin state<=148; end  else begin state<=155; end 
 
16'd148:if (Encrypted_pixels[374] <= 3105758) begin state<=149; end  else begin state<=152; end 
 
16'd149:if (Encrypted_pixels[514] <= 2274039) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd152:if (Encrypted_pixels[683] <= 3616013) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd155:if (Encrypted_pixels[270] <= 1663510) begin state<=156; end  else begin state<=159; end 
 
16'd156:if (Encrypted_pixels[216] <= 1671222) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd159:if (Encrypted_pixels[378] <= 3343373) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd162:if (Encrypted_pixels[347] <= 1541028) begin state<=163; end  else begin state<=178; end 
 
16'd163:if (Encrypted_pixels[344] <= 3181073) begin state<=164; end  else begin state<=171; end 
 
16'd164:if (Encrypted_pixels[520] <= 1636686) begin state<=165; end  else begin state<=168; end 
 
16'd165:if (Encrypted_pixels[518] <= 3665839) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd168:if (Encrypted_pixels[351] <= 1589437) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd171:if (Encrypted_pixels[453] <= 2049692) begin state<=172; end  else begin state<=175; end 
 
16'd172:if (Encrypted_pixels[512] <= 1782832) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd175:if (Encrypted_pixels[411] <= 5148778) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd178:if (Encrypted_pixels[358] <= 2049692) begin state<=179; end  else begin state<=186; end 
 
16'd179:if (Encrypted_pixels[513] <= 2566113) begin state<=180; end  else begin state<=183; end 
 
16'd180:if (Encrypted_pixels[356] <= 2766363) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd183:if (Encrypted_pixels[405] <= 4863055) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd186:if (Encrypted_pixels[400] <= 2439516) begin state<=187; end  else begin state<=190; end 
 
16'd187:if (Encrypted_pixels[510] <= 2459206) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd190:if (Encrypted_pixels[292] <= 2001392) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd193:if (Encrypted_pixels[346] <= 1523081) begin state<=194; end  else begin state<=225; end 
 
16'd194:if (Encrypted_pixels[348] <= 3013065) begin state<=195; end  else begin state<=210; end 
 
16'd195:if (Encrypted_pixels[343] <= 2068200) begin state<=196; end  else begin state<=203; end 
 
16'd196:if (Encrypted_pixels[155] <= 1523081) begin state<=197; end  else begin state<=200; end 
 
16'd197:if (Encrypted_pixels[652] <= 1591075) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd200:if (Encrypted_pixels[657] <= 3341404) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd203:if (Encrypted_pixels[213] <= 1541028) begin state<=204; end  else begin state<=207; end 
 
16'd204:if (Encrypted_pixels[574] <= 1782832) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd207:if (Encrypted_pixels[371] <= 1663510) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd210:if (Encrypted_pixels[353] <= 1532484) begin state<=211; end  else begin state<=218; end 
 
16'd211:if (Encrypted_pixels[513] <= 2899173) begin state<=212; end  else begin state<=215; end 
 
16'd212:if (Encrypted_pixels[122] <= 2707068) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd215:if (Encrypted_pixels[403] <= 3514612) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd218:if (Encrypted_pixels[466] <= 2342477) begin state<=219; end  else begin state<=222; end 
 
16'd219:if (Encrypted_pixels[405] <= 2272726) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd222:if (Encrypted_pixels[242] <= 1671222) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd225:if (Encrypted_pixels[655] <= 1523081) begin state<=226; end  else begin state<=241; end 
 
16'd226:if (Encrypted_pixels[271] <= 1532484) begin state<=227; end  else begin state<=234; end 
 
16'd227:if (Encrypted_pixels[484] <= 1541028) begin state<=228; end  else begin state<=231; end 
 
16'd228:if (Encrypted_pixels[516] <= 2274039) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd231:if (Encrypted_pixels[218] <= 1795610) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd234:if (Encrypted_pixels[354] <= 1671222) begin state<=235; end  else begin state<=238; end 
 
16'd235:if (Encrypted_pixels[357] <= 1573621) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd238:if (Encrypted_pixels[156] <= 1727290) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd241:if (Encrypted_pixels[354] <= 1523081) begin state<=242; end  else begin state<=249; end 
 
16'd242:if (Encrypted_pixels[515] <= 2550936) begin state<=243; end  else begin state<=246; end 
 
16'd243:if (Encrypted_pixels[357] <= 1663510) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd246:if (Encrypted_pixels[523] <= 1543571) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd249:if (Encrypted_pixels[433] <= 1532484) begin state<=250; end  else begin state<=253; end 
 
16'd250:if (Encrypted_pixels[484] <= 2127258) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd253:if (Encrypted_pixels[514] <= 1589437) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd256:if (Encrypted_pixels[489] <= 1998987) begin state<=257; end  else begin state<=384; end 
 
16'd257:if (Encrypted_pixels[290] <= 2057028) begin state<=258; end  else begin state<=321; end 
 
16'd258:if (Encrypted_pixels[486] <= 2384731) begin state<=259; end  else begin state<=290; end 
 
16'd259:if (Encrypted_pixels[296] <= 1541028) begin state<=260; end  else begin state<=275; end 
 
16'd260:if (Encrypted_pixels[490] <= 2808199) begin state<=261; end  else begin state<=268; end 
 
16'd261:if (Encrypted_pixels[299] <= 2057028) begin state<=262; end  else begin state<=265; end 
 
16'd262:if (Encrypted_pixels[186] <= 1532484) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd265:if (Encrypted_pixels[427] <= 4398142) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd268:if (Encrypted_pixels[600] <= 1541028) begin state<=269; end  else begin state<=272; end 
 
16'd269:if (Encrypted_pixels[430] <= 2418977) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1612420; state<=0;ml_inference_completed<=1; end 

16'd272:if (Encrypted_pixels[524] <= 2159720) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd275:if (Encrypted_pixels[153] <= 1523081) begin state<=276; end  else begin state<=283; end 
 
16'd276:if (Encrypted_pixels[208] <= 2322212) begin state<=277; end  else begin state<=280; end 
 
16'd277:if (Encrypted_pixels[539] <= 1541028) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd280:if (Encrypted_pixels[316] <= 2272726) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd283:if (Encrypted_pixels[488] <= 2396310) begin state<=284; end  else begin state<=287; end 
 
16'd284:if (Encrypted_pixels[315] <= 2959024) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd287:if (Encrypted_pixels[467] <= 2063926) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd290:if (Encrypted_pixels[657] <= 1573621) begin state<=291; end  else begin state<=306; end 
 
16'd291:if (Encrypted_pixels[152] <= 1782832) begin state<=292; end  else begin state<=299; end 
 
16'd292:if (Encrypted_pixels[270] <= 1998987) begin state<=293; end  else begin state<=296; end 
 
16'd293:if (Encrypted_pixels[601] <= 2462120) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd296:if (Encrypted_pixels[384] <= 2592967) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd299:if (Encrypted_pixels[343] <= 1589437) begin state<=300; end  else begin state<=303; end 
 
16'd300:if (Encrypted_pixels[439] <= 2355374) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd303:if (Encrypted_pixels[400] <= 1845940) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd306:if (Encrypted_pixels[439] <= 1707208) begin state<=307; end  else begin state<=314; end 
 
16'd307:if (Encrypted_pixels[464] <= 1532484) begin state<=308; end  else begin state<=311; end 
 
16'd308:if (Encrypted_pixels[125] <= 1663510) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd311:if (Encrypted_pixels[459] <= 2274039) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd314:if (Encrypted_pixels[179] <= 1674367) begin state<=315; end  else begin state<=318; end 
 
16'd315:if (Encrypted_pixels[352] <= 1782832) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd318:if (Encrypted_pixels[315] <= 1674367) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd321:if (Encrypted_pixels[297] <= 1573621) begin state<=322; end  else begin state<=353; end 
 
16'd322:if (Encrypted_pixels[486] <= 2384731) begin state<=323; end  else begin state<=338; end 
 
16'd323:if (Encrypted_pixels[186] <= 1541028) begin state<=324; end  else begin state<=331; end 
 
16'd324:if (Encrypted_pixels[294] <= 2791234) begin state<=325; end  else begin state<=328; end 
 
16'd325:if (Encrypted_pixels[299] <= 2355374) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd328:if (Encrypted_pixels[439] <= 1532484) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd331:if (Encrypted_pixels[301] <= 2633922) begin state<=332; end  else begin state<=335; end 
 
16'd332:if (Encrypted_pixels[295] <= 4550978) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd335:if (Encrypted_pixels[381] <= 1786619) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd338:if (Encrypted_pixels[656] <= 1956720) begin state<=339; end  else begin state<=346; end 
 
16'd339:if (Encrypted_pixels[430] <= 2661202) begin state<=340; end  else begin state<=343; end 
 
16'd340:if (Encrypted_pixels[319] <= 1541028) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd343:if (Encrypted_pixels[154] <= 1541028) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1591075; state<=0;ml_inference_completed<=1; end 

16'd346:if (Encrypted_pixels[300] <= 1589437) begin state<=347; end  else begin state<=350; end 
 
16'd347:if (Encrypted_pixels[294] <= 3452851) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd350:if (Encrypted_pixels[379] <= 5134336) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd353:if (Encrypted_pixels[598] <= 1523081) begin state<=354; end  else begin state<=369; end 
 
16'd354:if (Encrypted_pixels[210] <= 1573621) begin state<=355; end  else begin state<=362; end 
 
16'd355:if (Encrypted_pixels[404] <= 1612420) begin state<=356; end  else begin state<=359; end 
 
16'd356:if (Encrypted_pixels[322] <= 3288908) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1612420; state<=0;ml_inference_completed<=1; end 

16'd359:if (Encrypted_pixels[381] <= 3747834) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd362:if (Encrypted_pixels[653] <= 2486575) begin state<=363; end  else begin state<=366; end 
 
16'd363:if (Encrypted_pixels[154] <= 1612420) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd366:if (Encrypted_pixels[319] <= 2416121) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd369:if (Encrypted_pixels[486] <= 1663510) begin state<=370; end  else begin state<=377; end 
 
16'd370:if (Encrypted_pixels[427] <= 3951573) begin state<=371; end  else begin state<=374; end 
 
16'd371:if (Encrypted_pixels[318] <= 2633922) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd374:if (Encrypted_pixels[380] <= 4861419) begin Label<=1523081; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1589437; state<=0;ml_inference_completed<=1; end 

16'd377:if (Encrypted_pixels[400] <= 2009277) begin state<=378; end  else begin state<=381; end 
 
16'd378:if (Encrypted_pixels[573] <= 5016305) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd381:if (Encrypted_pixels[242] <= 2159720) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd384:if (Encrypted_pixels[234] <= 1523081) begin state<=385; end  else begin state<=446; end 
 
16'd385:if (Encrypted_pixels[375] <= 1523081) begin state<=386; end  else begin state<=415; end 
 
16'd386:if (Encrypted_pixels[149] <= 1573621) begin state<=387; end  else begin state<=402; end 
 
16'd387:if (Encrypted_pixels[300] <= 1573621) begin state<=388; end  else begin state<=395; end 
 
16'd388:if (Encrypted_pixels[494] <= 1573621) begin state<=389; end  else begin state<=392; end 
 
16'd389:if (Encrypted_pixels[539] <= 2042146) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd392:if (Encrypted_pixels[658] <= 2265460) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd395:if (Encrypted_pixels[265] <= 1532484) begin state<=396; end  else begin state<=399; end 
 
16'd396:if (Encrypted_pixels[542] <= 4344242) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd399:if (Encrypted_pixels[434] <= 3458409) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd402:if (Encrypted_pixels[287] <= 2189815) begin state<=403; end  else begin state<=410; end 
 
16'd403:if (Encrypted_pixels[543] <= 1573621) begin state<=404; end  else begin state<=407; end 
 
16'd404:if (Encrypted_pixels[545] <= 1734205) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd407:if (Encrypted_pixels[320] <= 3458409) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd410:if (Encrypted_pixels[180] <= 2163657) begin Label<=1591075; state<=0;ml_inference_completed<=1; end  else begin state<=412; end 

16'd412:if (Encrypted_pixels[432] <= 2031197) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd415:if (Encrypted_pixels[522] <= 1523081) begin state<=416; end  else begin state<=431; end 
 
16'd416:if (Encrypted_pixels[275] <= 1923688) begin state<=417; end  else begin state<=424; end 
 
16'd417:if (Encrypted_pixels[346] <= 1573621) begin state<=418; end  else begin state<=421; end 
 
16'd418:if (Encrypted_pixels[295] <= 5130488) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd421:if (Encrypted_pixels[712] <= 1532484) begin Label<=1573621; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd424:if (Encrypted_pixels[184] <= 1845940) begin state<=425; end  else begin state<=428; end 
 
16'd425:if (Encrypted_pixels[383] <= 1523081) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd428:if (Encrypted_pixels[354] <= 1663510) begin Label<=1589437; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd431:if (Encrypted_pixels[658] <= 1532484) begin state<=432; end  else begin state<=439; end 
 
16'd432:if (Encrypted_pixels[601] <= 3151652) begin state<=433; end  else begin state<=436; end 
 
16'd433:if (Encrypted_pixels[182] <= 1795610) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd436:if (Encrypted_pixels[594] <= 2622863) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd439:if (Encrypted_pixels[290] <= 1532484) begin state<=440; end  else begin state<=443; end 
 
16'd440:if (Encrypted_pixels[265] <= 1739301) begin Label<=1543571; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1532484; state<=0;ml_inference_completed<=1; end 

16'd443:if (Encrypted_pixels[429] <= 4664963) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd446:if (Encrypted_pixels[658] <= 1523081) begin state<=447; end  else begin state<=478; end 
 
16'd447:if (Encrypted_pixels[345] <= 1956720) begin state<=448; end  else begin state<=463; end 
 
16'd448:if (Encrypted_pixels[541] <= 1859112) begin state<=449; end  else begin state<=456; end 
 
16'd449:if (Encrypted_pixels[683] <= 1795610) begin state<=450; end  else begin state<=453; end 
 
16'd450:if (Encrypted_pixels[488] <= 2342477) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd453:if (Encrypted_pixels[349] <= 3626769) begin Label<=1612420; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd456:if (Encrypted_pixels[370] <= 1591075) begin state<=457; end  else begin state<=460; end 
 
16'd457:if (Encrypted_pixels[274] <= 1591075) begin Label<=1541028; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd460:if (Encrypted_pixels[240] <= 2378492) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1663510; state<=0;ml_inference_completed<=1; end 

16'd463:if (Encrypted_pixels[575] <= 5016305) begin state<=464; end  else begin state<=471; end 
 
16'd464:if (Encrypted_pixels[210] <= 1882847) begin state<=465; end  else begin state<=468; end 
 
16'd465:if (Encrypted_pixels[436] <= 2147458) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1573621; state<=0;ml_inference_completed<=1; end 

16'd468:if (Encrypted_pixels[568] <= 1589437) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd471:if (Encrypted_pixels[239] <= 3181073) begin state<=472; end  else begin state<=475; end 
 
16'd472:if (Encrypted_pixels[189] <= 1707208) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd475:if (Encrypted_pixels[425] <= 4070657) begin Label<=1591075; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1523081; state<=0;ml_inference_completed<=1; end 

16'd478:if (Encrypted_pixels[515] <= 2391907) begin state<=479; end  else begin state<=494; end 
 
16'd479:if (Encrypted_pixels[545] <= 1589437) begin state<=480; end  else begin state<=487; end 
 
16'd480:if (Encrypted_pixels[318] <= 2580963) begin state<=481; end  else begin state<=484; end 
 
16'd481:if (Encrypted_pixels[210] <= 1541028) begin Label<=1532484; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd484:if (Encrypted_pixels[513] <= 1573621) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd487:if (Encrypted_pixels[578] <= 1859112) begin state<=488; end  else begin state<=491; end 
 
16'd488:if (Encrypted_pixels[295] <= 4898653) begin Label<=1663510; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1612420; state<=0;ml_inference_completed<=1; end 

16'd491:if (Encrypted_pixels[575] <= 5137748) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 

16'd494:if (Encrypted_pixels[319] <= 1523081) begin state<=495; end  else begin state<=502; end 
 
16'd495:if (Encrypted_pixels[344] <= 1573621) begin state<=496; end  else begin state<=499; end 
 
16'd496:if (Encrypted_pixels[608] <= 1573621) begin Label<=1612420; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd499:if (Encrypted_pixels[440] <= 3812500) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1636686; state<=0;ml_inference_completed<=1; end 

16'd502:if (Encrypted_pixels[440] <= 2622863) begin state<=503; end  else begin state<=506; end 
 
16'd503:if (Encrypted_pixels[527] <= 2418977) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1541028; state<=0;ml_inference_completed<=1; end 

16'd506:if (Encrypted_pixels[547] <= 3894037) begin Label<=1636686; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1543571; state<=0;ml_inference_completed<=1; end 


        endcase
        end
    end




endmodule

module Binary_To_7Segment 
  (
   input       i_Clk,
	input [3:0] i_Binary_Num,
   output      o_Segment_A,
   output      o_Segment_B,
   output      o_Segment_C,
   output      o_Segment_D,
   output      o_Segment_E,
   output      o_Segment_F,
   output      o_Segment_G
   );
 
  reg [6:0]    r_Hex_Encoding = 7'h00;
   
  // Purpose: Creates a case statement for all possible input binary numbers.
  // Drives r_Hex_Encoding appropriately for each input combination.
  // Encoding at https://www.fpga4student.com/2017/09/seven-segment-led-display-controller-basys3-fpga.html
  always @(posedge i_Clk)
    begin
      case (i_Binary_Num)
        4'b0000 : r_Hex_Encoding <= 7'b0000001;
        4'b0001 : r_Hex_Encoding <= 7'b1001111;
        4'b0010 : r_Hex_Encoding <= 7'b0010010;
        4'b0011 : r_Hex_Encoding <= 7'b0000110;
        4'b0100 : r_Hex_Encoding <= 7'b1001100;         
        4'b0101 : r_Hex_Encoding <= 7'b0100100;
        4'b0110 : r_Hex_Encoding <= 7'b0100000;
        4'b0111 : r_Hex_Encoding <= 7'b0001111;
        4'b1000 : r_Hex_Encoding <= 7'b0000000;
        4'b1001 : r_Hex_Encoding <= 7'b0000100; 
		  4'b1010 : r_Hex_Encoding <= 7'b0001000; //a
		  4'b1011 : r_Hex_Encoding <= 7'b1100000; //b
		  4'b1100 : r_Hex_Encoding <= 7'b0110001;  //c
		  4'b1101 : r_Hex_Encoding <= 7'b1000010;  //d
		  4'b1110 : r_Hex_Encoding <= 7'b0110000;  //e
		  4'b1111 : r_Hex_Encoding <= 7'b0111000;  //f
        default: r_Hex_Encoding = 7'b1111111;
      endcase
    end // always @ (posedge i_Clk)
 
  // r_Hex_Encoding[7] is unused
  assign o_Segment_A = r_Hex_Encoding[6];
  assign o_Segment_B = r_Hex_Encoding[5];
  assign o_Segment_C = r_Hex_Encoding[4];
  assign o_Segment_D = r_Hex_Encoding[3];
  assign o_Segment_E = r_Hex_Encoding[2];
  assign o_Segment_F = r_Hex_Encoding[1];
  assign o_Segment_G = r_Hex_Encoding[0];
 
endmodule // Binary_To_7Segment



//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Receiver.  This receiver is able to
// receive 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When receive is complete o_rx_dv will be
// driven high for one clock cycle.
// https://www.nandland.com/vhdl/modules/module-uart-serial-port-rs232.html
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_rx   #(parameter CLKS_PER_BIT = 53)
  (
   input        i_Clock,
   input        i_Rx_Serial,
   output       o_Rx_DV,
   output [7:0] o_Rx_Byte
   );
    
  parameter s_IDLE         = 3'b000;
  parameter s_RX_START_BIT = 3'b001;
  parameter s_RX_DATA_BITS = 3'b010;
  parameter s_RX_STOP_BIT  = 3'b011; 
  parameter s_CLEANUP      = 3'b100;
   
  reg           r_Rx_Data_R = 1'b1;
  reg           r_Rx_Data   = 1'b1;
   
  reg [7:0]     r_Clock_Count = 0;
  reg [2:0]     r_Bit_Index   = 0; //8 bits total
  reg [7:0]     r_Rx_Byte     = 0;
  reg           r_Rx_DV       = 0;
  reg [2:0]     r_SM_Main     = 0;
   
  // Purpose: Double-register the incoming data.
  // This allows it to be used in the UART RX Clock Domain.
  // (It removes problems caused by metastability)
  always @(posedge i_Clock)
    begin
      r_Rx_Data_R <= i_Rx_Serial;
      r_Rx_Data   <= r_Rx_Data_R;
    end
   
   
  // Purpose: Control RX state machine
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            r_Rx_DV       <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (r_Rx_Data == 1'b0)          // Start bit detected
              r_SM_Main <= s_RX_START_BIT;
            else
              r_SM_Main <= s_IDLE;
          end
         
        // Check middle of start bit to make sure it's still low
        s_RX_START_BIT :
          begin
            if (r_Clock_Count == (CLKS_PER_BIT-1)/2)
              begin
                if (r_Rx_Data == 1'b0)
                  begin
                    r_Clock_Count <= 0;  // reset counter, found the middle
                    r_SM_Main     <= s_RX_DATA_BITS;
                  end
                else
                  r_SM_Main <= s_IDLE;
              end
            else
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_START_BIT;
              end
          end // case: s_RX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles to sample serial data
        s_RX_DATA_BITS :
          begin
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count          <= 0;
                r_Rx_Byte[r_Bit_Index] <= r_Rx_Data;
                 
                // Check if we have received all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_RX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_RX_STOP_BIT;
                  end
              end
          end // case: s_RX_DATA_BITS
     
     
        // Receive Stop bit.  Stop bit = 1
        s_RX_STOP_BIT :
          begin
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_STOP_BIT;
              end
            else
              begin
                r_Rx_DV       <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
              end
          end // case: s_RX_STOP_BIT
     
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_SM_Main <= s_IDLE;
            r_Rx_DV   <= 1'b0;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end   
   
  assign o_Rx_DV   = r_Rx_DV;
  assign o_Rx_Byte = r_Rx_Byte;
   
endmodule // uart_rx


//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Transmitter.  This transmitter is able
// to transmit 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When transmit is complete o_Tx_done will be
// driven high for one clock cycle.
//
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_tx 
  #(parameter CLKS_PER_BIT = 53)
  (
   input       i_Clock,
   input       i_Tx_DV,
   input [7:0] i_Tx_Byte, 
   output      o_Tx_Active,
   output reg  o_Tx_Serial,
   output      o_Tx_Done
   );
  
  parameter s_IDLE         = 3'b000;
  parameter s_TX_START_BIT = 3'b001;
  parameter s_TX_DATA_BITS = 3'b010;
  parameter s_TX_STOP_BIT  = 3'b011;
  parameter s_CLEANUP      = 3'b100;
   
  reg [2:0]    r_SM_Main     = 0;
  reg [7:0]    r_Clock_Count = 0;
  reg [2:0]    r_Bit_Index   = 0;
  reg [7:0]    r_Tx_Data     = 0;
  reg          r_Tx_Done     = 0;
  reg          r_Tx_Active   = 0;
     
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            o_Tx_Serial   <= 1'b1;         // Drive Line High for Idle
            r_Tx_Done     <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (i_Tx_DV == 1'b1)
              begin
                r_Tx_Active <= 1'b1;
                r_Tx_Data   <= i_Tx_Byte;
                r_SM_Main   <= s_TX_START_BIT;
              end
            else
              r_SM_Main <= s_IDLE;
          end // case: s_IDLE
         
         
        // Send out Start Bit. Start bit = 0
        s_TX_START_BIT :
          begin
            o_Tx_Serial <= 1'b0;
             
            // Wait CLKS_PER_BIT-1 clock cycles for start bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_START_BIT;
              end
            else
              begin
                r_Clock_Count <= 0;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
          end // case: s_TX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles for data bits to finish         
        s_TX_DATA_BITS :
          begin
            o_Tx_Serial <= r_Tx_Data[r_Bit_Index];
             
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count <= 0;
                 
                // Check if we have sent out all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_TX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_TX_STOP_BIT;
                  end
              end
          end // case: s_TX_DATA_BITS
         
         
        // Send out Stop bit.  Stop bit = 1
        s_TX_STOP_BIT :
          begin
            o_Tx_Serial <= 1'b1;
             
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_STOP_BIT;
              end
            else
              begin
                r_Tx_Done     <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
                r_Tx_Active   <= 1'b0;
              end
          end // case: s_Tx_STOP_BIT
         
         
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_Tx_Done <= 1'b1;
            r_SM_Main <= s_IDLE;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end
 
  assign o_Tx_Active = r_Tx_Active;
  assign o_Tx_Done   = r_Tx_Done;
   
endmodule

