
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_Standard(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		 reg    [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire RxD;
reg seg7_disp_off_signal;

parameter storage_length = 784;
reg transmit;
wire transmit_debounced;
wire tick;
wire [7:0] receive_data;
//reg [7:0] count_value;
wire receive_done;
wire [7:0] mem_data;
reg [9:0] mem_address;
reg [9:0] written_mem_address;
reg mem_wr;
reg first_val_receive;
reg txdone_flag;
reg [7:0] pixels[storage_length-1:0];
reg [7:0] Label;
reg [7:0] serial_transmit_reg;
reg Allpixel_receive_complete;
reg [15:0] state;
reg ml_inference_completed;


//=======================================================
//  Structural coding
//=======================================================


Binary_To_7Segment seg1 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label[3:0] : mem_address[3:0]),  .o_Segment_A(HEX0[0]), .o_Segment_B(HEX0[1]),  .o_Segment_C(HEX0[2]), 
                          .o_Segment_D(HEX0[3]), .o_Segment_E(HEX0[4]), .o_Segment_F(HEX0[5]), .o_Segment_G(HEX0[6]));
								  
Binary_To_7Segment seg2 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b0001 : mem_address[7:4]),  .o_Segment_A(HEX1[0]), .o_Segment_B(HEX1[1]),  .o_Segment_C(HEX1[2]), 
                          .o_Segment_D(HEX1[3]), .o_Segment_E(HEX1[4]), .o_Segment_F(HEX1[5]), .o_Segment_G(HEX1[6]));
								  
Binary_To_7Segment seg3 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1110 : mem_address[9:8]),  .o_Segment_A(HEX2[0]), .o_Segment_B(HEX2[1]),  .o_Segment_C(HEX2[2]), 
                          .o_Segment_D(HEX2[3]), .o_Segment_E(HEX2[4]), .o_Segment_F(HEX2[5]), .o_Segment_G(HEX2[6]));
								  
								  
Binary_To_7Segment seg4 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1011 : written_mem_address[3:0]),  .o_Segment_A(HEX3[0]), .o_Segment_B(HEX3[1]),  .o_Segment_C(HEX3[2]), 
                          .o_Segment_D(HEX3[3]), .o_Segment_E(HEX3[4]), .o_Segment_F(HEX3[5]), .o_Segment_G(HEX3[6]));
								  
Binary_To_7Segment seg5 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1010 : written_mem_address[7:4]),  .o_Segment_A(HEX4[0]), .o_Segment_B(HEX4[1]),  .o_Segment_C(HEX4[2]), 
                          .o_Segment_D(HEX4[3]), .o_Segment_E(HEX4[4]), .o_Segment_F(HEX4[5]), .o_Segment_G(HEX4[6]));
								  
Binary_To_7Segment seg6 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b0001 : written_mem_address[9:8]),  .o_Segment_A(HEX5[0]), .o_Segment_B(HEX5[1]),  .o_Segment_C(HEX5[2]), 
                          .o_Segment_D(HEX5[3]), .o_Segment_E(HEX5[4]), .o_Segment_F(HEX5[5]), .o_Segment_G(HEX5[6]));

					  
								  
assign RxD = GPIO[0];  //UART receiver pin for FPGA
// GPIO[1];  //UART transmitter Pin for FPGA


uart_rx R3 (.i_Clock(CLOCK_50), .i_Rx_Serial(RxD), .o_Rx_DV(receive_done), .o_Rx_Byte(receive_data) );

always @ (posedge receive_done)
begin
      if (SW[0] == 1)    begin LEDR[1] <= 0; end
      else begin LEDR[1] <= ~LEDR[1]; end
end

always @ (posedge CLOCK_50)
begin
    if (receive_done == 1)
        begin
        mem_address <= mem_address+1;   written_mem_address <= mem_address; 
        pixels[mem_address] <= receive_data;
        if (mem_address >= storage_length-1)
        begin Allpixel_receive_complete <=1; end
        else
        begin Allpixel_receive_complete <=0; end
        end
            
     if (SW[0] == 1)
         begin
            mem_address <= 0;
				seg7_disp_off_signal <=0;
         end
     
     if (tick == 1)
         begin
           if (txdone_flag == 0 )
               begin
                    txdone_flag <= 1;
               end
           else 
               begin
                    mem_address <= mem_address+1;
                    txdone_flag <= 0;
               end              
         end
     
     if (mem_address < written_mem_address && SW[1]== 1)
     begin
        transmit <= 1;    
        serial_transmit_reg <= pixels[mem_address];    
     end
     else if (mem_address == written_mem_address && SW[1]== 1)
     begin 
        transmit <= 1;   
        serial_transmit_reg <= Label;    
     end
     else
     begin
        transmit <=0; 
     end 
	  
	  if (SW[2] == 1)
         begin
				seg7_disp_off_signal <= 1;
         end
end

uart_tx T1 (.i_Clock(CLOCK_50), .i_Tx_DV(transmit), .i_Tx_Byte(serial_transmit_reg), .o_Tx_Active(), .o_Tx_Serial(GPIO[1]), .o_Tx_Done(tick) );



always @ (posedge CLOCK_50)
    begin
    if (SW[0] == 1)
         begin
            state <= 0;
         end
         
    if (Allpixel_receive_complete==1)
        begin
 case (state)
 16'd0:if (pixels[350] <= 119) begin state<=1; end  else begin state<=254; end 
 
16'd1:if (pixels[568] <= 0) begin state<=2; end  else begin state<=127; end 
 
16'd2:if (pixels[430] <= 0) begin state<=3; end  else begin state<=66; end 
 
16'd3:if (pixels[405] <= 0) begin state<=4; end  else begin state<=35; end 
 
16'd4:if (pixels[485] <= 12) begin state<=5; end  else begin state<=20; end 
 
16'd5:if (pixels[154] <= 0) begin state<=6; end  else begin state<=13; end 
 
16'd6:if (pixels[594] <= 21) begin state<=7; end  else begin state<=10; end 
 
16'd7:if (pixels[152] <= 7) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd10:if (pixels[434] <= 29) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd13:if (pixels[454] <= 2) begin state<=14; end  else begin state<=17; end 
 
16'd14:if (pixels[571] <= 9) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd17:if (pixels[594] <= 27) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd20:if (pixels[211] <= 12) begin state<=21; end  else begin state<=28; end 
 
16'd21:if (pixels[487] <= 135) begin state<=22; end  else begin state<=25; end 
 
16'd22:if (pixels[574] <= 99) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd25:if (pixels[427] <= 4) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd28:if (pixels[427] <= 0) begin state<=29; end  else begin state<=32; end 
 
16'd29:if (pixels[154] <= 1) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd32:if (pixels[470] <= 3) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd35:if (pixels[516] <= 14) begin state<=36; end  else begin state<=51; end 
 
16'd36:if (pixels[353] <= 2) begin state<=37; end  else begin state<=44; end 
 
16'd37:if (pixels[322] <= 8) begin state<=38; end  else begin state<=41; end 
 
16'd38:if (pixels[355] <= 12) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd41:if (pixels[518] <= 4) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd44:if (pixels[346] <= 1) begin state<=45; end  else begin state<=48; end 
 
16'd45:if (pixels[182] <= 92) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd48:if (pixels[210] <= 22) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd51:if (pixels[376] <= 3) begin state<=52; end  else begin state<=59; end 
 
16'd52:if (pixels[207] <= 0) begin state<=53; end  else begin state<=56; end 
 
16'd53:if (pixels[292] <= 7) begin Label<=1; state<=0;ml_inference_completed<=1; end 
       else begin Label<=7; state<=0;ml_inference_completed<=1; end 

16'd56:if (pixels[427] <= 3) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd59:if (pixels[658] <= 1) begin state<=60; end  else begin state<=63; end 
 
16'd60:if (pixels[326] <= 1) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd63:if (pixels[434] <= 182) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd66:if (pixels[211] <= 28) begin state<=67; end  else begin state<=96; end 
 
16'd67:if (pixels[98] <= 1) begin state<=68; end  else begin state<=83; end 
 
16'd68:if (pixels[267] <= 121) begin state<=69; end  else begin state<=76; end 
 
16'd69:if (pixels[95] <= 7) begin state<=70; end  else begin state<=73; end 
 
16'd70:if (pixels[155] <= 78) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd73:if (pixels[242] <= 104) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd76:if (pixels[381] <= 2) begin state<=77; end  else begin state<=80; end 
 
16'd77:if (pixels[412] <= 3) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=7; state<=0;ml_inference_completed<=1; end 

16'd80:if (pixels[406] <= 97) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd83:if (pixels[243] <= 36) begin state<=84; end  else begin state<=91; end 
 
16'd84:if (pixels[269] <= 50) begin state<=85; end  else begin state<=88; end 
 
16'd85:if (pixels[132] <= 215) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd88:if (pixels[290] <= 34) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd91:if (pixels[626] <= 28) begin state<=92; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 
 
16'd92:if (pixels[600] <= 251) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd96:if (pixels[156] <= 0) begin state<=97; end  else begin state<=112; end 
 
16'd97:if (pixels[381] <= 8) begin state<=98; end  else begin state<=105; end 
 
16'd98:if (pixels[411] <= 6) begin state<=99; end  else begin state<=102; end 
 
16'd99:if (pixels[217] <= 3) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd102:if (pixels[437] <= 38) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd105:if (pixels[317] <= 1) begin state<=106; end  else begin state<=109; end 
 
16'd106:if (pixels[342] <= 1) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd109:if (pixels[570] <= 101) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd112:if (pixels[101] <= 1) begin state<=113; end  else begin state<=120; end 
 
16'd113:if (pixels[656] <= 1) begin state<=114; end  else begin state<=117; end 
 
16'd114:if (pixels[572] <= 0) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd117:if (pixels[326] <= 0) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd120:if (pixels[299] <= 95) begin state<=121; end  else begin state<=124; end 
 
16'd121:if (pixels[486] <= 3) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd124:if (pixels[292] <= 50) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd127:if (pixels[435] <= 0) begin state<=128; end  else begin state<=191; end 
 
16'd128:if (pixels[489] <= 10) begin state<=129; end  else begin state<=160; end 
 
16'd129:if (pixels[380] <= 2) begin state<=130; end  else begin state<=145; end 
 
16'd130:if (pixels[324] <= 180) begin state<=131; end  else begin state<=138; end 
 
16'd131:if (pixels[72] <= 1) begin state<=132; end  else begin state<=135; end 
 
16'd132:if (pixels[214] <= 0) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd135:if (pixels[263] <= 2) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd138:if (pixels[271] <= 4) begin state<=139; end  else begin state<=142; end 
 
16'd139:if (pixels[240] <= 101) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd142:if (pixels[321] <= 251) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd145:if (pixels[484] <= 10) begin state<=146; end  else begin state<=153; end 
 
16'd146:if (pixels[374] <= 104) begin state<=147; end  else begin state<=150; end 
 
16'd147:if (pixels[514] <= 49) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd150:if (pixels[459] <= 135) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd153:if (pixels[269] <= 72) begin state<=154; end  else begin state<=157; end 
 
16'd154:if (pixels[658] <= 110) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd157:if (pixels[405] <= 230) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd160:if (pixels[320] <= 1) begin state<=161; end  else begin state<=176; end 
 
16'd161:if (pixels[345] <= 62) begin state<=162; end  else begin state<=169; end 
 
16'd162:if (pixels[343] <= 61) begin state<=163; end  else begin state<=166; end 
 
16'd163:if (pixels[377] <= 5) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd166:if (pixels[441] <= 240) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd169:if (pixels[442] <= 50) begin state<=170; end  else begin state<=173; end 
 
16'd170:if (pixels[431] <= 142) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd173:if (pixels[482] <= 131) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd176:if (pixels[385] <= 18) begin state<=177; end  else begin state<=184; end 
 
16'd177:if (pixels[513] <= 71) begin state<=178; end  else begin state<=181; end 
 
16'd178:if (pixels[553] <= 17) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd181:if (pixels[407] <= 16) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd184:if (pixels[400] <= 47) begin state<=185; end  else begin state<=188; end 
 
16'd185:if (pixels[521] <= 245) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd188:if (pixels[383] <= 253) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd191:if (pixels[346] <= 0) begin state<=192; end  else begin state<=223; end 
 
16'd192:if (pixels[348] <= 85) begin state<=193; end  else begin state<=208; end 
 
16'd193:if (pixels[371] <= 63) begin state<=194; end  else begin state<=201; end 
 
16'd194:if (pixels[679] <= 0) begin state<=195; end  else begin state<=198; end 
 
16'd195:if (pixels[484] <= 0) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd198:if (pixels[156] <= 48) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd201:if (pixels[213] <= 5) begin state<=202; end  else begin state<=205; end 
 
16'd202:if (pixels[216] <= 26) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd205:if (pixels[655] <= 32) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd208:if (pixels[353] <= 1) begin state<=209; end  else begin state<=216; end 
 
16'd209:if (pixels[513] <= 97) begin state<=210; end  else begin state<=213; end 
 
16'd210:if (pixels[150] <= 24) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd213:if (pixels[430] <= 48) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd216:if (pixels[466] <= 47) begin state<=217; end  else begin state<=220; end 
 
16'd217:if (pixels[405] <= 48) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd220:if (pixels[242] <= 13) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd223:if (pixels[655] <= 0) begin state<=224; end  else begin state<=239; end 
 
16'd224:if (pixels[271] <= 1) begin state<=225; end  else begin state<=232; end 
 
16'd225:if (pixels[484] <= 5) begin state<=226; end  else begin state<=229; end 
 
16'd226:if (pixels[488] <= 18) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd229:if (pixels[219] <= 2) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd232:if (pixels[354] <= 10) begin state<=233; end  else begin state<=236; end 
 
16'd233:if (pixels[385] <= 5) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd236:if (pixels[156] <= 13) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd239:if (pixels[354] <= 3) begin state<=240; end  else begin state<=247; end 
 
16'd240:if (pixels[514] <= 76) begin state<=241; end  else begin state<=244; end 
 
16'd241:if (pixels[357] <= 9) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd244:if (pixels[384] <= 162) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd247:if (pixels[433] <= 1) begin state<=248; end  else begin state<=251; end 
 
16'd248:if (pixels[484] <= 39) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd251:if (pixels[487] <= 2) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd254:if (pixels[489] <= 26) begin state<=255; end  else begin state<=382; end 
 
16'd255:if (pixels[290] <= 34) begin state<=256; end  else begin state<=319; end 
 
16'd256:if (pixels[486] <= 58) begin state<=257; end  else begin state<=288; end 
 
16'd257:if (pixels[296] <= 2) begin state<=258; end  else begin state<=273; end 
 
16'd258:if (pixels[490] <= 87) begin state<=259; end  else begin state<=266; end 
 
16'd259:if (pixels[315] <= 19) begin state<=260; end  else begin state<=263; end 
 
16'd260:if (pixels[177] <= 1) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd263:if (pixels[328] <= 34) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd266:if (pixels[600] <= 1) begin state<=267; end  else begin state<=270; end 
 
16'd267:if (pixels[430] <= 62) begin Label<=1; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd270:if (pixels[466] <= 37) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd273:if (pixels[153] <= 0) begin state<=274; end  else begin state<=281; end 
 
16'd274:if (pixels[208] <= 51) begin state<=275; end  else begin state<=278; end 
 
16'd275:if (pixels[568] <= 4) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd278:if (pixels[316] <= 48) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd281:if (pixels[316] <= 104) begin state<=282; end  else begin state<=285; end 
 
16'd282:if (pixels[490] <= 157) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd285:if (pixels[456] <= 138) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd288:if (pixels[656] <= 1) begin state<=289; end  else begin state<=304; end 
 
16'd289:if (pixels[152] <= 8) begin state<=290; end  else begin state<=297; end 
 
16'd290:if (pixels[601] <= 82) begin state<=291; end  else begin state<=294; end 
 
16'd291:if (pixels[161] <= 46) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd294:if (pixels[271] <= 2) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd297:if (pixels[432] <= 12) begin state<=298; end  else begin state<=301; end 
 
16'd298:if (pixels[296] <= 16) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd301:if (pixels[315] <= 22) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd304:if (pixels[439] <= 12) begin state<=305; end  else begin state<=312; end 
 
16'd305:if (pixels[464] <= 1) begin state<=306; end  else begin state<=309; end 
 
16'd306:if (pixels[125] <= 11) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd309:if (pixels[177] <= 184) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd312:if (pixels[180] <= 6) begin state<=313; end  else begin state<=316; end 
 
16'd313:if (pixels[380] <= 149) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd316:if (pixels[315] <= 19) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd319:if (pixels[297] <= 7) begin state<=320; end  else begin state<=351; end 
 
16'd320:if (pixels[486] <= 58) begin state<=321; end  else begin state<=336; end 
 
16'd321:if (pixels[186] <= 1) begin state<=322; end  else begin state<=329; end 
 
16'd322:if (pixels[293] <= 214) begin state<=323; end  else begin state<=326; end 
 
16'd323:if (pixels[598] <= 2) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd326:if (pixels[463] <= 175) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd329:if (pixels[301] <= 79) begin state<=330; end  else begin state<=333; end 
 
16'd330:if (pixels[294] <= 251) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd333:if (pixels[381] <= 13) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd336:if (pixels[656] <= 12) begin state<=337; end  else begin state<=344; end 
 
16'd337:if (pixels[430] <= 81) begin state<=338; end  else begin state<=341; end 
 
16'd338:if (pixels[400] <= 167) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd341:if (pixels[514] <= 8) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd344:if (pixels[300] <= 11) begin state<=345; end  else begin state<=348; end 
 
16'd345:if (pixels[294] <= 134) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd348:if (pixels[407] <= 100) begin Label<=0; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd351:if (pixels[598] <= 0) begin state<=352; end  else begin state<=367; end 
 
16'd352:if (pixels[210] <= 3) begin state<=353; end  else begin state<=360; end 
 
16'd353:if (pixels[321] <= 208) begin state<=354; end  else begin state<=357; end 
 
16'd354:if (pixels[381] <= 156) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd357:if (pixels[404] <= 113) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd360:if (pixels[653] <= 67) begin state<=361; end  else begin state<=364; end 
 
16'd361:if (pixels[154] <= 43) begin Label<=9; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd364:if (pixels[319] <= 62) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd367:if (pixels[486] <= 9) begin state<=368; end  else begin state<=375; end 
 
16'd368:if (pixels[427] <= 168) begin state<=369; end  else begin state<=372; end 
 
16'd369:if (pixels[269] <= 1) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd372:if (pixels[358] <= 67) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd375:if (pixels[400] <= 23) begin state<=376; end  else begin state<=379; end 
 
16'd376:if (pixels[573] <= 238) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd379:if (pixels[242] <= 42) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd382:if (pixels[235] <= 0) begin state<=383; end  else begin state<=446; end 
 
16'd383:if (pixels[550] <= 0) begin state<=384; end  else begin state<=415; end 
 
16'd384:if (pixels[300] <= 0) begin state<=385; end  else begin state<=400; end 
 
16'd385:if (pixels[438] <= 3) begin state<=386; end  else begin state<=393; end 
 
16'd386:if (pixels[150] <= 32) begin state<=387; end  else begin state<=390; end 
 
16'd387:if (pixels[374] <= 19) begin Label<=1; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd390:if (pixels[348] <= 32) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd393:if (pixels[373] <= 18) begin state<=394; end  else begin state<=397; end 
 
16'd394:if (pixels[548] <= 3) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd397:if (pixels[538] <= 24) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd400:if (pixels[183] <= 1) begin state<=401; end  else begin state<=408; end 
 
16'd401:if (pixels[188] <= 49) begin state<=402; end  else begin state<=405; end 
 
16'd402:if (pixels[382] <= 30) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=7; state<=0;ml_inference_completed<=1; end 

16'd405:if (pixels[324] <= 207) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd408:if (pixels[375] <= 45) begin state<=409; end  else begin state<=412; end 
 
16'd409:if (pixels[571] <= 247) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd412:if (pixels[293] <= 7) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd415:if (pixels[153] <= 75) begin state<=416; end  else begin state<=431; end 
 
16'd416:if (pixels[573] <= 96) begin state<=417; end  else begin state<=424; end 
 
16'd417:if (pixels[555] <= 7) begin state<=418; end  else begin state<=421; end 
 
16'd418:if (pixels[429] <= 245) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd421:if (pixels[201] <= 50) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=4; state<=0;ml_inference_completed<=1; end 

16'd424:if (pixels[536] <= 146) begin state<=425; end  else begin state<=428; end 
 
16'd425:if (pixels[658] <= 68) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd428:if (pixels[400] <= 46) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 

16'd431:if (pixels[542] <= 98) begin state<=432; end  else begin state<=439; end 
 
16'd432:if (pixels[260] <= 14) begin state<=433; end  else begin state<=436; end 
 
16'd433:if (pixels[266] <= 124) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=1; state<=0;ml_inference_completed<=1; end 

16'd436:if (pixels[660] <= 3) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd439:if (pixels[319] <= 39) begin state<=440; end  else begin state<=443; end 
 
16'd440:if (pixels[343] <= 28) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd443:if (pixels[233] <= 29) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd446:if (pixels[657] <= 2) begin state<=447; end  else begin state<=478; end 
 
16'd447:if (pixels[345] <= 0) begin state<=448; end  else begin state<=463; end 
 
16'd448:if (pixels[515] <= 0) begin state<=449; end  else begin state<=456; end 
 
16'd449:if (pixels[297] <= 1) begin state<=450; end  else begin state<=453; end 
 
16'd450:if (pixels[231] <= 29) begin Label<=1; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd453:if (pixels[404] <= 39) begin Label<=7; state<=0;ml_inference_completed<=1; end 
       else begin Label<=3; state<=0;ml_inference_completed<=1; end 

16'd456:if (pixels[319] <= 121) begin state<=457; end  else begin state<=460; end 
 
16'd457:if (pixels[687] <= 9) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=7; state<=0;ml_inference_completed<=1; end 

16'd460:if (pixels[526] <= 43) begin Label<=6; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd463:if (pixels[574] <= 209) begin state<=464; end  else begin state<=471; end 
 
16'd464:if (pixels[353] <= 219) begin state<=465; end  else begin state<=468; end 
 
16'd465:if (pixels[527] <= 221) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=2; state<=0;ml_inference_completed<=1; end 

16'd468:if (pixels[239] <= 2) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd471:if (pixels[212] <= 35) begin state<=472; end  else begin state<=475; end 
 
16'd472:if (pixels[543] <= 3) begin Label<=4; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd475:if (pixels[571] <= 236) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=6; state<=0;ml_inference_completed<=1; end 

16'd478:if (pixels[515] <= 61) begin state<=479; end  else begin state<=494; end 
 
16'd479:if (pixels[517] <= 53) begin state<=480; end  else begin state<=487; end 
 
16'd480:if (pixels[513] <= 66) begin state<=481; end  else begin state<=484; end 
 
16'd481:if (pixels[318] <= 246) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=5; state<=0;ml_inference_completed<=1; end 

16'd484:if (pixels[458] <= 67) begin Label<=3; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd487:if (pixels[294] <= 242) begin state<=488; end  else begin state<=491; end 
 
16'd488:if (pixels[712] <= 0) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=9; state<=0;ml_inference_completed<=1; end 

16'd491:if (pixels[270] <= 8) begin Label<=1; state<=0;ml_inference_completed<=1; end 
       else begin Label<=7; state<=0;ml_inference_completed<=1; end 

16'd494:if (pixels[319] <= 0) begin state<=495; end  else begin state<=502; end 
 
16'd495:if (pixels[608] <= 5) begin state<=496; end  else begin state<=499; end 
 
16'd496:if (pixels[268] <= 187) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=7; state<=0;ml_inference_completed<=1; end 

16'd499:if (pixels[345] <= 34) begin Label<=2; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd502:if (pixels[545] <= 217) begin state<=503; end  else begin state<=506; end 
 
16'd503:if (pixels[406] <= 8) begin Label<=5; state<=0;ml_inference_completed<=1; end 
       else begin Label<=8; state<=0;ml_inference_completed<=1; end 

16'd506:if (pixels[441] <= 170) begin Label<=8; state<=0;ml_inference_completed<=1; end 
       else begin Label<=0; state<=0;ml_inference_completed<=1; end 
        endcase
        end
    end




endmodule

module Binary_To_7Segment 
  (
   input       i_Clk,
	input [3:0] i_Binary_Num,
   output      o_Segment_A,
   output      o_Segment_B,
   output      o_Segment_C,
   output      o_Segment_D,
   output      o_Segment_E,
   output      o_Segment_F,
   output      o_Segment_G
   );
 
  reg [6:0]    r_Hex_Encoding = 7'h00;
   
  // Purpose: Creates a case statement for all possible input binary numbers.
  // Drives r_Hex_Encoding appropriately for each input combination.
  // Encoding at https://www.fpga4student.com/2017/09/seven-segment-led-display-controller-basys3-fpga.html
  always @(posedge i_Clk)
    begin
      case (i_Binary_Num)
        4'b0000 : r_Hex_Encoding <= 7'b0000001;
        4'b0001 : r_Hex_Encoding <= 7'b1001111;
        4'b0010 : r_Hex_Encoding <= 7'b0010010;
        4'b0011 : r_Hex_Encoding <= 7'b0000110;
        4'b0100 : r_Hex_Encoding <= 7'b1001100;         
        4'b0101 : r_Hex_Encoding <= 7'b0100100;
        4'b0110 : r_Hex_Encoding <= 7'b0100000;
        4'b0111 : r_Hex_Encoding <= 7'b0001111;
        4'b1000 : r_Hex_Encoding <= 7'b0000000;
        4'b1001 : r_Hex_Encoding <= 7'b0000100; 
		  4'b1010 : r_Hex_Encoding <= 7'b0001000; //a
		  4'b1011 : r_Hex_Encoding <= 7'b1100000; //b
		  4'b1100 : r_Hex_Encoding <= 7'b0110001;  //c
		  4'b1101 : r_Hex_Encoding <= 7'b1000010;  //d
		  4'b1110 : r_Hex_Encoding <= 7'b0110000;  //e
		  4'b1111 : r_Hex_Encoding <= 7'b0111000;  //f
        default: r_Hex_Encoding = 7'b1111111;
      endcase
    end // always @ (posedge i_Clk)
 
  // r_Hex_Encoding[7] is unused
  assign o_Segment_A = r_Hex_Encoding[6];
  assign o_Segment_B = r_Hex_Encoding[5];
  assign o_Segment_C = r_Hex_Encoding[4];
  assign o_Segment_D = r_Hex_Encoding[3];
  assign o_Segment_E = r_Hex_Encoding[2];
  assign o_Segment_F = r_Hex_Encoding[1];
  assign o_Segment_G = r_Hex_Encoding[0];
 
endmodule // Binary_To_7Segment



//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Receiver.  This receiver is able to
// receive 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When receive is complete o_rx_dv will be
// driven high for one clock cycle.
// https://www.nandland.com/vhdl/modules/module-uart-serial-port-rs232.html
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_rx   #(parameter CLKS_PER_BIT = 53)
  (
   input        i_Clock,
   input        i_Rx_Serial,
   output       o_Rx_DV,
   output [7:0] o_Rx_Byte
   );
    
  parameter s_IDLE         = 3'b000;
  parameter s_RX_START_BIT = 3'b001;
  parameter s_RX_DATA_BITS = 3'b010;
  parameter s_RX_STOP_BIT  = 3'b011; 
  parameter s_CLEANUP      = 3'b100;
   
  reg           r_Rx_Data_R = 1'b1;
  reg           r_Rx_Data   = 1'b1;
   
  reg [7:0]     r_Clock_Count = 0;
  reg [2:0]     r_Bit_Index   = 0; //8 bits total
  reg [7:0]     r_Rx_Byte     = 0;
  reg           r_Rx_DV       = 0;
  reg [2:0]     r_SM_Main     = 0;
   
  // Purpose: Double-register the incoming data.
  // This allows it to be used in the UART RX Clock Domain.
  // (It removes problems caused by metastability)
  always @(posedge i_Clock)
    begin
      r_Rx_Data_R <= i_Rx_Serial;
      r_Rx_Data   <= r_Rx_Data_R;
    end
   
   
  // Purpose: Control RX state machine
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            r_Rx_DV       <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (r_Rx_Data == 1'b0)          // Start bit detected
              r_SM_Main <= s_RX_START_BIT;
            else
              r_SM_Main <= s_IDLE;
          end
         
        // Check middle of start bit to make sure it's still low
        s_RX_START_BIT :
          begin
            if (r_Clock_Count == (CLKS_PER_BIT-1)/2)
              begin
                if (r_Rx_Data == 1'b0)
                  begin
                    r_Clock_Count <= 0;  // reset counter, found the middle
                    r_SM_Main     <= s_RX_DATA_BITS;
                  end
                else
                  r_SM_Main <= s_IDLE;
              end
            else
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_START_BIT;
              end
          end // case: s_RX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles to sample serial data
        s_RX_DATA_BITS :
          begin
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count          <= 0;
                r_Rx_Byte[r_Bit_Index] <= r_Rx_Data;
                 
                // Check if we have received all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_RX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_RX_STOP_BIT;
                  end
              end
          end // case: s_RX_DATA_BITS
     
     
        // Receive Stop bit.  Stop bit = 1
        s_RX_STOP_BIT :
          begin
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_STOP_BIT;
              end
            else
              begin
                r_Rx_DV       <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
              end
          end // case: s_RX_STOP_BIT
     
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_SM_Main <= s_IDLE;
            r_Rx_DV   <= 1'b0;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end   
   
  assign o_Rx_DV   = r_Rx_DV;
  assign o_Rx_Byte = r_Rx_Byte;
   
endmodule // uart_rx


//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Transmitter.  This transmitter is able
// to transmit 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When transmit is complete o_Tx_done will be
// driven high for one clock cycle.
//
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_tx 
  #(parameter CLKS_PER_BIT = 53)
  (
   input       i_Clock,
   input       i_Tx_DV,
   input [7:0] i_Tx_Byte, 
   output      o_Tx_Active,
   output reg  o_Tx_Serial,
   output      o_Tx_Done
   );
  
  parameter s_IDLE         = 3'b000;
  parameter s_TX_START_BIT = 3'b001;
  parameter s_TX_DATA_BITS = 3'b010;
  parameter s_TX_STOP_BIT  = 3'b011;
  parameter s_CLEANUP      = 3'b100;
   
  reg [2:0]    r_SM_Main     = 0;
  reg [7:0]    r_Clock_Count = 0;
  reg [2:0]    r_Bit_Index   = 0;
  reg [7:0]    r_Tx_Data     = 0;
  reg          r_Tx_Done     = 0;
  reg          r_Tx_Active   = 0;
     
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            o_Tx_Serial   <= 1'b1;         // Drive Line High for Idle
            r_Tx_Done     <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (i_Tx_DV == 1'b1)
              begin
                r_Tx_Active <= 1'b1;
                r_Tx_Data   <= i_Tx_Byte;
                r_SM_Main   <= s_TX_START_BIT;
              end
            else
              r_SM_Main <= s_IDLE;
          end // case: s_IDLE
         
         
        // Send out Start Bit. Start bit = 0
        s_TX_START_BIT :
          begin
            o_Tx_Serial <= 1'b0;
             
            // Wait CLKS_PER_BIT-1 clock cycles for start bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_START_BIT;
              end
            else
              begin
                r_Clock_Count <= 0;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
          end // case: s_TX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles for data bits to finish         
        s_TX_DATA_BITS :
          begin
            o_Tx_Serial <= r_Tx_Data[r_Bit_Index];
             
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count <= 0;
                 
                // Check if we have sent out all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_TX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_TX_STOP_BIT;
                  end
              end
          end // case: s_TX_DATA_BITS
         
         
        // Send out Stop bit.  Stop bit = 1
        s_TX_STOP_BIT :
          begin
            o_Tx_Serial <= 1'b1;
             
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_STOP_BIT;
              end
            else
              begin
                r_Tx_Done     <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
                r_Tx_Active   <= 1'b0;
              end
          end // case: s_Tx_STOP_BIT
         
         
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_Tx_Done <= 1'b1;
            r_SM_Main <= s_IDLE;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end
 
  assign o_Tx_Active = r_Tx_Active;
  assign o_Tx_Done   = r_Tx_Done;
   
endmodule

